---
- name: assert that dante user name starts with dante_
  assert:
    that: dante_user.startswith('dante_')
    fail_msg: "dante username '{{ dante_user }}' must start with 'dante_'"
  tags: lin_dante_user

- name: create dante proxy user
  # see: https://docs.ansible.com/ansible/latest/modules/user_module.html#user-module
  user:
    name: "{{ dante_user }}"
    state: present
    # see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#hash-filters
    password: "{{ dante_pass | password_hash('sha512', dante_salt) }}"
    update_password: always
    group: users
    shell: /usr/sbin/nologin
    home: /usr/sbin
    create_home: no
    generate_ssh_key: no
  notify: restart dante service
  tags: lin_dante_user


- name: configure dante server
  template:
    src: danted.conf
    dest: /etc/danted.conf
    mode: 0644
  notify: restart dante service
  tags: lin_dante_conf


- name: install foreign dante package on xenial (with workarounds)
  block:
    # dante package for xenial lacks required features (user-based access control?)
    # see: https://launchpad.net/ubuntu/bionic/amd64/dante-server/1.4.2+dfsg-2build1
    #
    # accept pains and install foreign package from bionic
    # some problems first manifested itself when run with mitogen
    #
    # the bionic .deb package has xz-compressed control file
    # xz-utils can be installed by lin-system as part of python-apt (or herein as a fallback)
    # fixed error: "Unable to install package: There is no member named 'control'"
    # see: https://github.com/geerlingguy/docker-ubuntu1804-ansible/issues/7#issuecomment-450792375
    #
    # retries:
    # - additionally help to fix the "no member named 'control'" issue
    # - overcome network problems on a cheap VPS with low memory
    #   ("timed out" in error message)
    #
    # commented out 'force' option once used to fix python-apt issues with foreign deb
    # fixed error: "Failed to satisfy all dependencies (broken cache)"
    #
    # reset_connection restarts mitogen runner to reset (broken) apt state
    # see: https://github.com/dw/mitogen/issues/407#issuecomment-433453574
    #
    - name: fix for xz-compressed control in foreign dante deb
      apt:
        name:
          - python-apt
          - python3-apt
        state: present

    - name: restart mitogen runner to reset apt state
      meta: reset_connection

    - name: install dante server
      apt:
        deb: "{{ dante_deb_url }}"
        force: true
        force_apt_get: true
      register: dante_install_xenial_result
      until: dante_install_xenial_result is successful
  when: ansible_lsb.codename == 'xenial'
  tags: lin_dante_install

- name: install dante server (ubuntu bionic)
  apt:
    name: dante-server
  when: ansible_lsb.codename == 'bionic'
  register: dante_install_bionic_result
  tags: lin_dante_install


- name: temporarily stop dante service after fresh install
  # note: this step is a workaround.
  #       without this "recycling" the service might end up disabled.
  systemd:
    name: danted
    state: stopped
    enabled: no
    daemon_reload: yes
  when: dante_install_xenial_result is changed or dante_install_bionic_result is changed
  tags: lin_dante_service

- name: enable dante service
  systemd:
    name: danted
    state: started
    enabled: yes
    daemon_reload: yes
  tags: lin_dante_service


- name: open dante port, if allowed
  ufw:
    rule: "{{ dante_direct |ternary('allow','deny') }}"
    port: "{{ dante_port |string }}"
  no_log: true
  when: lin_use_firewall |bool
  tags: lin_dante_firewall

- meta: flush_handlers
...
